language: php

php:
  - 5.6
  - 7.0

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - composer global require squizlabs/php_codesniffer
  - phpenv rehash
  - phpcs --version
  - phpunit
